//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejemplo.Model
{
    using GenericRepository.EntityFramework;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class AdventureWorks2014Entities : EntitiesContext
    {
        public AdventureWorks2014Entities()
            : base("name=AdventureWorks2014Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual IDbSet<Product> Products { get; set; }
        public virtual IDbSet<ProductCategory> ProductCategories { get; set; }
        public virtual IDbSet<ProductModel> ProductModels { get; set; }
        public virtual IDbSet<ProductSubcategory> ProductSubcategories { get; set; }
    }
}
